[bar.default]
background_opacity = 0.43999999016523361
contact_shadow = true
end = [
    "bar",
    "widget_2",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "brightness",
    "widget",
    "battery",
    "custom_button_2",
    "control-center",
    "session"
]
font_family = "JetBrains Mono"
font_weight = 700
margin_edge = 6
margin_ends = 223
radius = 24
scale = 0.85000000521540642
start = [ "custom_button_3", "wallpaper", "workspaces", "cat", "cpu", "ram", "media", "audio_visualizer" ]
thickness = 30

[battery]
warning_threshold = 20

[calendar]
enabled = true

    [calendar.account.google_utama]
    name = "Biruworld"
    server_url = "https://calendar.google.com/calendar/ical/kusanandabiruu%40gmail.com/private-2b48a5e4ae052845750db2433d5a547f/basic.ics"
    type = "ics"

[control_center]
sidebar = "full"
sidebar_section = "full"

    [control_center.calendar]
    show_week_numbers = true

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
background_opacity = 0.57999998703598976
enabled = true
layer = "overlay"
magnification_scale = 1.7500000111758709
position = "right"
reserve_space = false
show_dots = true

[hooks]
battery_charging = "hrr"
battery_discharging = "hrr"
battery_plugged = "hrr"

[hot_corners]
enabled = true

    [hot_corners.top_right]
    action = "control_center"

[idle]
behavior_order = [ "screen-off", "lock", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 250.0

[location]
address = "Jimbaran, Indonesia"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.00006103515625
    cy = 852.49969482421875
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
temperature_day = 5800

[notification]
layer = "overlay"

[plugin_settings."avivbintangaringga/nix-monitor"]
branch = "nixos-26.05"
update_check_interval = 100

[plugins]
enabled = [ "dotnetrob/cat", "blackbartblues/audio-switcher", "asterlusnce/agenda", "noctalia/timer" ]

[shell]
font_family = "JetBrains Mono"
password_style = "random"
polkit_agent = true
screen_time_enabled = true

    [shell.panel]
    clipboard_placement = "attached"
    control_center_placement = "floating"
    transparency_mode = "glass"

[theme]
builtin = "Ayu"
community_palette = "Cherry Blossom"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "gtk3", "ghostty", "kitty", "niri", "qt" ]
    community_ids = [ "spicetify", "zen-browser", "discord", "neovim", "obsidian" ]

[wallpaper]
directory = "/home/asterlusnce/Wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/asterlusnce/Wallpapers/Original Hy Tao.jpg"

    [wallpaper.last]
    path = "/home/asterlusnce/Wallpapers/Original Hy Tao.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/asterlusnce/Wallpapers/Original Hy Tao.jpg"

    [[wallpaper.favorite]]
    path = "/home/asterlusnce/Wallpapers/2898909.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    builtin_palette = "Ayu"
    palette_source = "builtin"
    path = "/home/asterlusnce/Wallpapers/99cf11143b02cfcf1653d9b8a367613f.jpg"
    theme_mode = "dark"

[widget.audio_visualizer]
bands = 8
centered = false
color_1 = "on_surface"
scale = 1.6500000000000001

[widget.bar]
type = "noctalia/timer:bar"

[widget.cat]
cat_size = 36
show_cpu_percent = true
type = "dotnetrob/cat:cat"

[widget.cpu]
show_glyph = false
stat = "cpu_temp"
visualization = "none"

[widget.custom_button_2]
glyph = "powersaver"
tooltip = "powerctl"
type = "custom_button"

    [widget.custom_button_2.actions]
    left = "exec kitty --class powerctl -e sudo /home/asterlusnce/.local/bin/powerctl"
    right = "exec kitty --class powerctl -e sudo /home/asterlusnce/.local/bin/powerctl"

[widget.custom_button_3]
custom_image = "/home/asterlusnce/Downloads/1_NJ1kWalHS7V0FP_hudH64w-removebg-preview.png"
scale = 1.5
type = "custom_button"

    [widget.custom_button_3.actions]
    left = "exec notify-send \"WELCOME TO A FLAKE OF NIXOS!\""
    right = "exec rofi -show drun"

[widget.network]
show_label = false

[widget.ram]
stat = "ram_pct"
visualization = "none"

[widget.tray]
capsule_fill = "primary"

[widget.widget]
type = "blackbartblues/audio-switcher:widget"

[widget.widget_2]
type = "alexander/screen-toolkit:widget"

[widget.workspaces]
style = "focus_hint"
